# Generated by Django 2.0.4 on 2018-12-17 06:34
import string
from datetime import datetime, timedelta
from random import randrange, choice

from django.db import migrations


bools = (True, False)
daterange = (
    datetime(datetime.now().year, 1, 1),
    datetime(datetime.now().year, 12, 31),
)


def random_str(size=15, chars=string.printable):
    return ''.join(choice(chars) for x in range(size))


def random_date(start, end):
    """
    This function will return a random datetime between two datetime
    objects.
    """
    delta = end - start
    int_delta = (delta.days * 24 * 60 * 60) + delta.seconds
    random_second = randrange(int_delta)
    return start + timedelta(seconds=random_second)


def generate_data(apps, schema_editor):
    Obj = apps.get_model('specobj', 'Obj')
    Spec = apps.get_model('specobj', 'Spec')

    for item in range(10):
        obj = Obj.objects.create(
            is_deleted=choice(bools),
            name=random_str()
        )
        for nested in range(10):
            spec = Spec.objects.create(
                link=obj,
                is_actual=choice(bools),
                date=random_date(*daterange)
            )


class Migration(migrations.Migration):

    dependencies = [
        ('specobj', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_data),
    ]
