# Generated by Django 2.0.4 on 2018-12-17 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AstronomicalObjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Астрономический объект',
                'verbose_name_plural': 'Астрономические объекты',
            },
        ),
        migrations.CreateModel(
            name='AstronomicalObjectScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Масштабность объекта',
                'verbose_name_plural': 'Масштабность объектав',
            },
        ),
        migrations.CreateModel(
            name='AstronomicalObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип небесного тела',
                'verbose_name_plural': 'Типы небесных тел',
            },
        ),
        migrations.CreateModel(
            name='ClassificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Tип классификации',
                'verbose_name_plural': 'Типы классификации',
            },
        ),
        migrations.AddField(
            model_name='astronomicalobjectgroup',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.ClassificationType'),
        ),
        migrations.AddField(
            model_name='astronomicalobjectgroup',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.AstronomicalObjectScale'),
        ),
        migrations.AddField(
            model_name='astronomicalobjectgroup',
            name='asto_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.AstronomicalObjectType'),
        ),
    ]
